# Generated by Django 5.1.1 on 2024-10-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_order_cart_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='menu_images/'),
        ),
    ]
