# Generated by Django 5.1.1 on 2024-10-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_menuitem_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category']},
        ),
    ]
